name: Auto Add Mario Level Ayam

on:
  schedule:
    - cron: '*/30 * * * *'  # setiap 30 menit (UTC)
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add new level
        run: |
          LEVEL_FILE="levels/level-$(date +%Y%m%d-%H%M)-ayam.txt"
          mkdir -p levels
          echo "Level ayam generated on $(date)" > "$LEVEL_FILE"
          echo "#######" >> "$LEVEL_FILE"
          echo "#     #" >> "$LEVEL_FILE"
          echo "#  M  #" >> "$LEVEL_FILE"
          echo "#######" >> "$LEVEL_FILE"

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push if changed
        run: |
          git add levels/
          git commit -m "Auto add new level ayam for $(date +%Y-%m-%d-%H:%M) [skip ci]" || echo "No changes to commit"
          git push